[package]
name = "hoofprint"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14.0"
axum = { version = "0.8.8", features = ["tokio", "macros"] }
axum-server = { version = "0.8.0", features = [
    "tokio-rustls",
    "rustls",
    "rustls-pki-types",
] }
clap = { version = "4.5.53", features = ["derive", "env"] }
sea-orm = { version = "1.1.19", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
] }
sea-orm-migration = { version = "1.1.19", features = [
    "with-time",
    "with-uuid",
    "with-json",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
] }
simplelog = "0.12.2"
tokio = { version = "1.48.0", features = ["full", "tracing"] }
tower-http = { version = "0.6.8", features = [
    "fs",
    "trace",
    "compression-br",
    "compression-gzip",
    "compression-deflate",
] }
tracing = { version = "0.1.44", features = ["log", "release_max_level_debug"] }
uuid = { version = "1.19.0", features = ["v7"] }
